############################
# STEP 1 build executable binary
############################
FROM alpine AS builder
ARG WGETPROXY
RUN sed -i 's#http://dl-cdn.alpinelinux.org#https://mirrors.aliyun.com#g' /etc/apk/repositories \
    && apk update \
    && apk add --no-cache wget bash ca-certificates \
    && wget $WGETPROXY -qO- https://raw.githubusercontent.com/daiaji/simple-torrent/master/scripts/qi.sh | bash

############################
# STEP 2 build a small image
############################
FROM scratch

COPY --from=builder /usr/local/bin/cloud-torrent /usr/local/bin/cloud-torrent
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

ENTRYPOINT ["cloud-torrent"]
